### ISSUE TITLE
Nix.rs on GSOC 2018

### ISSUE THREAD

**Issue by AndersonTorres** [solson/nixrs#1]
Hello, @solson ! What do you think about your project on the list for NixOS GSOC 2018? I have put it already.

**Comment by solson** [comment]
That sounds very interesting! But what exactly would it entail? I'm not that familiar with GSOC, or the NixOS GSOC in particular.

**Comment by AndersonTorres** [comment]
I'm not familiar with GSOC either :) Most the things I know are described [here](http://write.flossmanuals.net/gsoc-mentoring/what-is-gsoc/)

For now, I have put your project on our [list](https://github.com/nix-community/google-summer-of-code/blob/master/2018/projects.md). I think you could mentor a student interested in working with a real world Rust program.
